#spring.application.name=gateway-service
spring:
  #  security:
  #    oauth2:
  #      resourceserver:
  #        jwt:
  #          issuer-uri: "http://localhost:8080/realms/myrealm"
  config:
    import: optional:configserver:http://54.151.152.174:8081
  application:
    name: gateway-service

#server:
#  port: 4040
