#spring.application.name=book-service
spring:
  config:
    import: optional:configserver:http://localhost:8081
  application:
    name: book-service
#  datasource:
#    hikari:
#      connectionTimeout: 60000
#      idleTimeout: 600000
#      maxLifeTime: 600000
#  profiles:
#    active: prod

#https://www:
#  baeldung:
#    com/spring-boot-hikari:
#
#https://medium:
#  com/javarevisited/hikari-connection-pooling-5600d765e5ae:
#
#https://github:
#  com/brettwooldridge/HikariCP/issues/1600:
#https://stackoverflow:
#  com/questions/62176990/hikaricp-mysql-no-operations-allowed-after-connection-closed-possibly-conside:
#
#      https://stackoverflow:
#        com/questions/22296601/postgresql-connection-timeout:
#
#  https://stackoverflow:
#    com/questions/5108876/kill-a-postgresql-session-connection:
#  https://github:
#    com/gaurav157243/aws-projects/blob/main/DBOnEC2/README.MD
#
#
#https://stackoverflow:
#  com/questions/22296601/postgresql-connection-timeout:#spring:
#https://tldp:
#  org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html
#https://www:
#  baeldung:
#    com/sql/psqlexception-fatal-sorry-too-many-clients-already-solution

#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=book
#    username: postgres
#    password: admin
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    #    hibernate:
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#server:
#  port: 8888

#hibernate:
#  show_sql: true
#  format_sql: true
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE





#security:
#  basic:
#    enabled=false:
#debug: true
#
#logging:
#  level:
#    org.springframework.web: DEBUG
#    guru.springframework.controllers: DEBUG
#    org.hibernate: DEBUG
#    org: INFO